<?php
session_start();
include("config.php");

// Check if user is logged in
if(!isset($_SESSION['user_id'])){
    header("Location: login.php");
    exit();
}

$report_type = isset($_GET['type']) ? $_GET['type'] : 'daily';
$start_date = isset($_GET['start_date']) ? $_GET['start_date'] : date('Y-m-d');
$end_date = isset($_GET['end_date']) ? $_GET['end_date'] : date('Y-m-d');

// Get data based on report type
switch($report_type){
    case 'daily':
        $query = "SELECT s.*, m.medicine_name FROM sales s
                  JOIN medicines m ON s.medicine_id = m.medicine_id
                  WHERE DATE(s.sale_date) = '$start_date'
                  ORDER BY s.sale_date DESC";
        $title = "Daily Sales Report - $start_date";
        break;
    case 'monthly':
        $query = "SELECT s.*, m.medicine_name FROM sales s
                  JOIN medicines m ON s.medicine_id = m.medicine_id
                  WHERE DATE(s.sale_date) BETWEEN '$start_date' AND '$end_date'
                  ORDER BY s.sale_date DESC";
        $title = "Monthly Sales Report - $start_date to $end_date";
        break;
    case 'inventory':
        $query = "SELECT * FROM medicines ORDER BY medicine_name ASC";
        $title = "Inventory Report";
        break;
    case 'orders':
        $query = "SELECT o.*, c.customer_name FROM orders o
                  JOIN customers c ON o.customer_id = c.customer_id
                  WHERE DATE(o.order_date) BETWEEN '$start_date' AND '$end_date'
                  ORDER BY o.order_date DESC";
        $title = "Orders Report - $start_date to $end_date";
        break;
    default:
        $query = "SELECT s.*, m.medicine_name FROM sales s
                  JOIN medicines m ON s.medicine_id = m.medicine_id
                  WHERE DATE(s.sale_date) = CURDATE()
                  ORDER BY s.sale_date DESC";
        $title = "Daily Sales Report";
}

$result = mysqli_query($conn, $query);
?>

<!DOCTYPE html>
<html>
<head>
    <title><?php echo $title; ?></title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
            font-weight: bold;
        }
        .total-section {
            margin-top: 30px;
            padding: 20px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
        }
        .print-btn {
            position: fixed;
            top: 20px;
            right: 20px;
            padding: 10px 20px;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
        @media print {
            .print-btn {
                display: none;
            }
        }
    </style>
</head>
<body>
    <button class="print-btn" onclick="window.print()">🖨️ Print Report</button>
    
    <div class="header">
        <h1>🏥 Pharmacy Management System</h1>
        <h2><?php echo $title; ?></h2>
        <p>Generated on: <?php echo date('Y-m-d H:i:s'); ?></p>
        <p>Generated by: <?php echo $_SESSION['fullname']; ?></p>
    </div>

    <table>
        <thead>
            <tr>
                <?php if($report_type == 'daily' || $report_type == 'monthly'): ?>
                <th>ID</th>
                <th>Medicine Name</th>
                <th>Quantity Sold</th>
                <th>Total Amount (TZS)</th>
                <th>Date</th>
                <?php elseif($report_type == 'inventory'): ?>
                <th>ID</th>
                <th>Medicine Name</th>
                <th>Category</th>
                <th>Quantity</th>
                <th>Buying Price</th>
                <th>Selling Price</th>
                <th>Expiry Date</th>
                <?php elseif($report_type == 'orders'): ?>
                <th>Order ID</th>
                <th>Customer</th>
                <th>Total Amount</th>
                <th>Status</th>
                <th>Date</th>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody>
            <?php 
            $total = 0;
            while($row = mysqli_fetch_assoc($result)): 
            ?>
            <tr>
                <?php if($report_type == 'daily' || $report_type == 'monthly'): ?>
                <td><?php echo $row['sale_id']; ?></td>
                <td><?php echo $row['medicine_name']; ?></td>
                <td><?php echo $row['quantity_sold']; ?></td>
                <td><?php echo number_format($row['total_amount'], 2); ?></td>
                <td><?php echo date('Y-m-d H:i', strtotime($row['sale_date'])); ?></td>
                <?php $total += $row['total_amount']; ?>
                <?php elseif($report_type == 'inventory'): ?>
                <td><?php echo $row['medicine_id']; ?></td>
                <td><?php echo $row['medicine_name']; ?></td>
                <td><?php echo $row['category']; ?></td>
                <td><?php echo $row['quantity']; ?></td>
                <td><?php echo number_format($row['buying_price'], 2); ?></td>
                <td><?php echo number_format($row['selling_price'], 2); ?></td>
                <td><?php echo $row['expiry_date']; ?></td>
                <?php elseif($report_type == 'orders'): ?>
                <td>#<?php echo $row['order_id']; ?></td>
                <td><?php echo $row['customer_name']; ?></td>
                <td><?php echo number_format($row['total_amount'], 2); ?></td>
                <td><?php echo ucfirst($row['status']); ?></td>
                <td><?php echo date('Y-m-d H:i', strtotime($row['order_date'])); ?></td>
                <?php $total += $row['total_amount']; ?>
                <?php endif; ?>
            </tr>
            <?php endwhile; ?>
        </tbody>
    </table>

    <?php if($report_type == 'daily' || $report_type == 'monthly' || $report_type == 'orders'): ?>
    <div class="total-section">
        <h3>Total Amount: TZS <?php echo number_format($total, 2); ?></h3>
    </div>
    <?php endif; ?>

    <div style="margin-top: 50px; text-align: center; color: #999; font-size: 12px;">
        <p>This is an official report from Pharmacy Management System</p>
        <p>© <?php echo date('Y'); ?> Pharmacy Management System</p>
    </div>
</body>
</html>
